[build]
  command = "npm run build"
  publish = "out"
  
[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "true"
  
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  
[dev]
  command = "npm run dev"
  port = 3000
  publish = "out" 